version: 1
disable_existing_loggers: False
formatters:
    simple:
      format: "%(asctime)s - [%(module)s:%(funcName)s():%(lineno)d] - %(levelname)s - %(message)s"
      class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: simple
    filename: info.log
    backupCount: 10
    encoding: utf8
    when: D
    interval: 1
loggers:
  default:
    level: DEBUG
    handlers: [info_file_handler]
    propagate: True
root:
  level: INFO
  handlers: [console,info_file_handler]
